"""init faq table

Revision ID: 119a63102c65
Revises: 55b61b0a739a
Create Date: 2023-09-12 03:55:04.013769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119a63102c65'
down_revision = '55b61b0a739a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faqs')
    # ### end Alembic commands ###
