"""add is_bot in chat

Revision ID: 46050b0beea3
Revises: b7915b0dd12f
Create Date: 2023-09-12 00:53:04.799651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46050b0beea3'
down_revision = 'b7915b0dd12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bot', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('is_bot')

    # ### end Alembic commands ###
