"""add the flags in chat table

Revision ID: 55b61b0a739a
Revises: 46050b0beea3
Create Date: 2023-09-12 02:24:53.192176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b61b0a739a'
down_revision = '46050b0beea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_include', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('is_include')
        batch_op.drop_column('is_show')

    # ### end Alembic commands ###
